### ISSUE TITLE
Anthony Salvation (Alx Student)

### ISSUE THREAD

**Issue by Honour-1234** [TechByDami/alx-pre_course#2]
Description: I am now a Alx Student, this is my first repository as a full stack engineer.
Public repo
No README, gitignore, or license.

**Comment by TechByDami** [comment]
Will check it up now. Thanks for the observations

**Comment by Honour-1234** [comment]
Okay, thanks

**Comment by TechByDami** [comment]
https://github.com/TechByDami/alx-pre_course/tree/master/0x01-git

Link to the gitignore and also the README.md file. Do help me check for any errors.

And again, it's a bootcamp project, I'm not instructed to add a license.  But after I'm graded, I can decide to add it.
Thanks alot.
